version: '2'

services:
  db:
    build: ../../images/mysql
    container_name: ${PROJECT}db
    networks:
      - devnet
    restart: always
    ports:
      - ${MYSQL_PORT}:3306
    volumes_from:
      - files
    environment:
      MYSQL_DATABASE: ${DB_CATALOG}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWD}

  adminer:
    image: adminer
    container_name: ${PROJECT}adminer
    networks:
      - devnet
    links:
      - db:db
    restart: always
    ports:
      - ${ADMINER_PORT}:8080
    environment:
      UPLOAD: 1024M

  files:
    image: alpine:latest
    container_name: ${PROJECT}files
    volumes:
      - ${DATA_PATH}/logs/mysql:/var/log/mysql
      - ${DATA_PATH}/db:/var/lib/mysql
    networks:
      - devnet

networks:
  devnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${SUBNET}